version: "3"

services:
  
  prometheus:
    restart: always
    container_name: prometheus-test
    image: prom/prometheus:v2.53.2
    volumes:
      - ./configuration/prometheus:/etc/prometheus
      - prometheus-test-data:/prometheus

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    ports:
      - 9091:9090

  grafana:
    image: grafana/grafana:11.1.3
    restart: always
    container_name: grafana-test
    volumes:
      - grafana-storage-test:/var/lib/grafana
    ports:
      - 3001:3000

volumes:
  prometheus-test-data:
  grafana-storage-test: