version: "3"

services:

  prometheus:
    restart: always
    container_name: prometheus-prod
    image: prom/prometheus:v2.53.2
    volumes:
      - ./configuration/prometheus:/etc/prometheus
      - /opt/monitoring/prod_stack/prometheus_data:/prometheus
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 500M
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=30d'
    ports:
      - 9091:9090

  grafana:
    image: grafana/grafana:11.1.3
    restart: unless-stopped
    container_name: grafana-prod
    volumes:
      - /opt/monitoring/prod_stack/grafana_data:/var/lib/grafana
      - /opt/monitoring/prod_stack/certs/grafana.crt:/etc/grafana/certs/grafana.crt
      - /opt/monitoring/prod_stack/certs/grafana.key:/etc/grafana/certs/grafana.key
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 400M
        reservations:
          memory: 200M
    ports:
      - 3001:3000
    environment:
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/certs/grafana.crt
      - GF_SERVER_CERT_KEY=/etc/grafana/certs/grafana.key
      - GF_RENDERING_SERVER_URL=http://10.8.201.14:8081/render
      - GF_RENDERING_CALLBACK_URL=https://10.8.201.14:3001/
      - GF_LOG_FILTERS=rendering:debug
      - GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE=true
  renderer:
    restart: always
    image: grafana/grafana-image-renderer:latest
    environment:
      - IGNORE_HTTPS_ERRORS=true
      - GF_RENDERING_IGNORE_HTTPS_ERRORS=true
    ports:
      - 8081:8081