version: "3"

services:
  
  prometheus:
    restart: always
    container_name: prometheus-test
    image: prom/prometheus:v2.53.2
    privileged: true
    volumes:
      - ./configuration/prometheus:/etc/prometheus
      - prometheus-test-data:/prometheus

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
    ports:
      - 9091:9090

volumes:
  prometheus-test-data:
